<?php
/**
 * File Type: Shortcodes Function
 */
if (!class_exists('wp_rem_shortcode_functions')) {

    class wp_rem_shortcode_functions {

        /**
         * Start construct Functions
         */
        public function __construct() {

            /*
             * Add shortcode button on top of editor.
             */
            add_action('media_buttons', array($this, 'wp_rem_shortcode_button'), 11);
            wp_rem_include_shortcode_files();
            wp_rem_include_frontend_shortcode_files();
        }

        /*
         * Function to add shortcode.
         * To add shortcode use the filter.
         */

        public function wp_rem_shortcode_names() {

            $shortcode_array = array();

            $shortcode_array = apply_filters('wp_rem_shortcodes_list', $shortcode_array);
            ksort($shortcode_array);
            return $shortcode_array;
        }

        /*
         * Function to add Shortcodes Categories.
         * To add shortcode category use the filter.
         */

        public function wp_rem_elements_categories() {
            $categories_array = array(
                'typography' => wp_rem_plugin_text_srt('wp_rem_shortcodes_typography'),
                'commonelements' => wp_rem_plugin_text_srt('wp_rem_shortcodes_common_elements'),
                'mediaelement' => wp_rem_plugin_text_srt('wp_rem_shortcodes_media_element'),
                'contentblocks' => wp_rem_plugin_text_srt('wp_rem_shortcodes_content_blocks'),
                'loops' => wp_rem_plugin_text_srt('wp_rem_shortcodes_loops'));

            $categories_array = apply_filters('wp_rem_shortcodes_categories_list', $categories_array);

            return $categories_array;
        }

        /*
         * Function to add shortcode select options in button.
         * Do not edit this file unless required
         */

        public function wp_rem_shortcode_button($die = 0, $shortcode = 'shortcode') {

            global $wp_rem_form_fields;
            $i = 1;
            $rand = rand(1, 999);
            $wp_rem_page_elements_name = array();
            $wp_rem_page_elements_name = $this->wp_rem_shortcode_names();
            $wp_rem_page_categories_name = $this->wp_rem_elements_categories();

            $wp_rem_insert_btn = true;
            $screen = get_current_screen();
            if (is_admin() && isset($screen->parent_file) && $screen->parent_file == 'users.php') {
                $wp_rem_insert_btn = false;
            }
            ?> 
            <div class="cs-page-composer  <?php echo sanitize_html_class($shortcode); ?> composer-<?php echo intval($rand) ?>" id="composer-<?php echo intval($rand) ?>" style="display:none;">
                <div class="page-elements">
                    <div class="cs-heading-area">
                        <h5>
                            <i class="icon-plus-circle"></i> <?php echo wp_rem_plugin_text_srt('wp_rem_shortcodes_add_element'); ?>
                        </h5>
                        <span class='cs-btnclose' onclick='javascript:removeoverlay("composer-<?php echo esc_js($rand) ?>", "append")'>
                            <i class="icon-times"></i>
                        </span>
                    </div>
                    <script>
                        jQuery(document).ready(function ($) {
                            wp_rem_page_composer_filterable('<?php echo esc_js($rand) ?>');
                        });
                    </script>
                    <div class="cs-filter-content shortcode">
                        <p>
                            <?php
                            $wp_rem_opt_array = array(
                                'std' => '',
                                'cust_id' => 'quicksearch' . $rand,
                                'extra_atr' => ' placeholder="' . wp_rem_plugin_text_srt('wp_rem_property_search') . '"',
                                'cust_name' => '',
                                'required' => false,
                            );
                            $wp_rem_form_fields->wp_rem_form_text_render($wp_rem_opt_array);
                            ?>
                        </p>
                        <div class="cs-filtermenu-wrap">
                            <h6><?php echo wp_rem_plugin_text_srt('wp_rem_shortcodes_filter_by'); ?></h6>
                            <ul class="cs-filter-menu" id="filters<?php echo intval($rand) ?>">
                                <li data-filter="all" class="active"><?php echo wp_rem_plugin_text_srt('wp_rem_shortcodes_show_all'); ?></li>
                                <?php
                                foreach ($wp_rem_page_categories_name as $key => $value) {
                                    echo '<li data-filter="' . $key . '">' . $value . '</li>';
                                }
                                ?>
                            </ul>
                        </div>
                        <div class="cs-filter-inner" id="page_element_container<?php echo intval($rand) ?>">
                            <?php
                            foreach ($wp_rem_page_elements_name as $key => $element_value) {
                                echo '<div class="element-item ' . $element_value['categories'] . ' pb_' . esc_js($key) . '">';
                                $icon = isset($element_value['icon']) ? $element_value['icon'] : 'accordion-icon';
                                ?>
                                <a href='javascript:wp_rem_shortocde_selection("<?php echo esc_js($key); ?>","<?php echo admin_url('admin-ajax.php'); ?>","composer-<?php echo intval($rand) ?>")'><?php $this->wp_rem_page_composer_elements($element_value['title'], $icon) ?></a>
                            </div>
            <?php } ?>
                    </div>
                </div>
            </div>
            <div class="cs-page-composer-shortcode"></div>
            </div>
            <?php
        }

        public function wp_rem_page_composer_elements($element, $icon) {
            echo '<i class="fa ' . $icon . '"></i><span data-title="' . $element . '"> ' . $element . '</span>';
        }

    }

    global $wp_rem_shortcode_functions;
    $wp_rem_shortcode_functions = new wp_rem_shortcode_functions();
}